#lang s-exp "../../main.rkt"

(require rackunit
         "../helper+scm.rkt")

(rename-part 'derivative 'D)

(provide the-tests)
(define the-tests
  (test-suite
   "mechanics/qualitative"
   (test-case
    "iterated-map"
    ;; Let T be a map of the state space onto itself, as might be generated by a surface of section.
    ;; A trajectory sequence is generated by successive iteration of the map T.
    ;; The map carries one point of the trajectory sequence to the next: x(n + 1) = T(x(n))
    (define T
      (let ([T (literal-function 'T (-> (UP Real Real) (UP Real Real)))])
        (λ (x y cont fail)
          (define n (T (up x y)))
          (cont (ref n 0) (ref n 1)))))
    (define (T* X) (T (ref X 0) (ref X 1) up error))
    (check-simplified? ((iterated-map T 3) 'x 'y up error)
                       (T* (T* (T* (up 'x 'y)))))
    (check-exn #px"iterated-map: cannot invert map"
               (λ () ((iterated-map T -3) 'x 'y up error))))
   (test-case
    "standard-map"
    (check-= (flo:pv 0.) 0. 1e-15)
    (check-= (flo:pv :pi) :pi 1e-15)
    (check-= (flo:pv :2pi) 0. 1e-15)
    (check-= (flo:pv (+ 1. :2pi)) 1. 1e-15)
    ;; standard map is: (Chirikov-Taylor map) : (map θ I)
    ; I' = (I + K sin θ) mod 2π
    ; θ' = (θ + I') mod 2π
    ; with fixed points at (0, 0) and (0 , π)
    (check-within ((standard-map 0.95) :pi/6 2. up error)
                  (up (+ :pi/6 2.475) 2.475) 1e-15)
    (check-within ((standard-map 0.95) 0. 0. up error)
                  (up 0. 0.) 1e-15)
    (check-within ((standard-map 0.95) :pi 0. up error)
                  (up :pi 0.) 1e-15)
    #;
    (let ()
      (local-require plot)
      ;; equivalent for the explore-map feature
      (define L
        (for/fold ([rslt (list* (list (list 1e-3 0.))
                               (list (list 0. 1e-3))
                               (list (list (+ :pi 1e-3) 0.))
                               (list (list :pi 1e-3))
                               (list (list 2. 2.))
                               (list (list 4. 2.))
                               (list (list 4. 1.))
                               (list (list 3. 3.))
                               (build-list 15 (λ (_) (list (list (* (random) :2pi) (* (random) :2pi))))))])
                  ([i (in-range 1000)])
          (for/list ([l (in-list rslt)])
            (cons ((standard-map 0.95) (caar l) (cadar l) list error) l))))
      (displayln
       (plot (for/list ([l (in-list L)] [i (in-naturals 1)])
               (points l #:color i #:sym 'dot))))))
   (test-case
    "unstable-manifold"
    ;; where T is the map, xe and ye are the coordinates of the fixed point, dx and dy are components
    ;; of the linearized eigenvector, rho is the characteristic multiplier, eps is a scale within
    ;; which the linearized map is a good enough approximation to T, and param is a continuous
    ;; parameter (like arc-length) along the manifold.
    (check-within ((unstable-manifold (standard-map 0.95)
                                      3.14 0.
                                      1. 1.
                                      2.0 1e-10) 3.5)
                  '(3.1415679233561775 . 6.28162137668141)
                  1e-15)
    (check-within ((unstable-manifold (standard-map 0.95)
                                      3.14 1.
                                      1. 1.
                                      2.0 1e-10) 3.5)
                  '(3.80094801918791 . 1.1523126285874772)
                  1e-15)
    (check-exn #px"Failed"
               (λ () ((unstable-manifold (λ (x y cont fail) (fail)) 0. 0. 1. 1. 2. 1.) 3.))))
   (test-case
    "fixed-point-eigen"
    (check-within (fixed-point-eigen (standard-map .95) :pi 0. 5. list)
                  '(-73.29037694363771 1.0000000000000135 -73.3403771414955 1.0365485577336557 1.0000000000000135 0.9865483598758763)
                  1e-12)
    (check-within (fixed-point-eigen (standard-map .95) 0. 0. 5. list)
                  '(-71.31628251906025 0.9999999999999982 -73.26628232120248 0.9624537374406331 0.9999999999999982 -0.987546064701594)
                  1e-12))
   (test-case
    "radially-mapping-points"
    (check-= (radially-mapping-points (iterated-map (standard-map .95) 6) :pi 0. 1. 1.)
             0.7853981633974483 1e-12)
    (check-= (radially-mapping-points (iterated-map (standard-map .95) 6) 4. 2.5 1. 1e-4)
             3.92474365234375 1e-12)
    (check-false (radially-mapping-points (iterated-map (standard-map .95) 6) 1. 1. 3. 1e-4)))
   (test-case
    "which-way"
    ;; TODO which-way? can enter infinite loop (for example with 1. 0. 0.)
    (check-equal? (which-way? 3.6 5.6 2.5 (standard-map .95))  1)
    ;; (check-equal? (which-way? 3.6 5.6 2.5 (standard-map .95))  1) ;; infinite loop
    (check-equal? (which-way?  3.8 5.6 2.5 (standard-map .95)) -1)
    (check-equal? (which-way?  3.1 2.1 0.5 (standard-map .95))  1)
    (check-equal? (which-way?  7.5 1.4 1.7 (standard-map .95)) -1)
    (check-equal? (which-way?  7.4 5.1 4.9 (standard-map .95)) -1)
    (check-equal? (which-way? 10.7 2.9 5.9 (standard-map .95))  1)
    (check-exn #px"Map failed" (λ () (which-way? 1 2 3 (λ (x y cont fail) (fail))))))
   (test-case
    "find-invariant-curve"
    (check-= (find-invariant-curve (standard-map 0.95) 3.6 5.6 0.5 4.9 1e-14)
             4.697506796118786 1e-12))
   ;**************************************************************************************************
   (test-case
    "qualitative"
    (check-= (find-invariant-curve (standard-map 0.95)
                      (- 1 (/ 1 (/ (+ 1 (sqrt 5)) 2)))
                      0.0
                      2.0
                      2.2
                      1e-5)
             2.114462280273437 1e12))
   ;; TODO scmutils/examples has more things to test
   ))

(module+ test
  (require rackunit/text-ui)
  (run-tests the-tests))