#lang racket/base

(require rackunit
         "../../main.rkt"
         "../helper+scm.rkt"
         )

(provide the-tests)
(define the-tests
  (test-suite
   "calculus/metric"
   ;;(set! *divide-out-terms* #f)
   ;;(set! *factoring* #t)
   (test-case
    "coordinate-system->metric-components / embedding-map->metric-components"
    (check-simplified? ((coordinate-system->metric-components R1-rect) 'x)
                       '(down (down 1)))
    (check-simplified? ((coordinate-system->metric-components R2-rect) (up 'x 'y))
                       '(down (down 1 0) (down 0 1)))
    (check-simplified? ((coordinate-system->metric-components R2-polar) (up 'x 'y))
                       '(down (down 1 0) (down 0 (expt x 2)))))
   (test-case
    "coordiante-system->metric"
    (check-equal? (argument-types (coordinate-system->metric R1-rect))
                  (list vector-field? vector-field?))
    (check-equal? (argument-types (coordinate-system->metric R2-rect))
                  (list vector-field? vector-field?))
    (check-simplified? (((coordinate-system->metric R1-rect)
                         (literal-vector-field 'V1 R1-rect)
                         (literal-vector-field 'V2 R1-rect))
                        ((point R1-rect) 'x))
                       '(* (V2^0 x) (V1^0 x)))
    (check-simplified? (((coordinate-system->metric R2-rect)
                         (coordinate-system->vector-basis R2-rect)
                         (coordinate-system->vector-basis R2-rect))
                        ((point R2-rect) (up 'x 'y)))
                       '(up
                         (down (down (down 1 0) (down 0 1)) (down (down 0 0) (down 0 0)))
                         (down (down (down 0 0) (down 0 0)) (down (down 1 0) (down 0 1)))))
    (check-simplified? (((coordinate-system->metric R2-polar)
                         (coordinate-system->vector-basis R2-polar)
                         (coordinate-system->vector-basis R2-rect))
                        ((point R2-polar) (up 'r 'α)))
                       '(up (down (down (down (cos α) 0) (down 0 (* (expt r 2) (cos α))))
                                  (down (down (sin α) 0) (down 0 (* (expt r 2) (sin α)))))
                            (down (down (down (/ (* -1 (sin α)) r) 0) (down 0 (* -1 r (sin α))))
                                  (down (down (/ (cos α) r) 0) (down 0 (* r (cos α))))))))
   (test-case
    "coordinate-system->inverse-metric"
    (check-equal? (argument-types (coordinate-system->inverse-metric R1-rect))
                  (list 1form-field? 1form-field?))
    (check-equal? (argument-types (coordinate-system->inverse-metric R2-polar))
                  (list 1form-field? 1form-field?))
    (check-simplified? (((coordinate-system->inverse-metric R1-rect)
                         (literal-1form-field 'F1 R1-rect)
                         (literal-1form-field 'F2 R1-rect))
                        ((point R1-rect) 'x))
                       '(* (F2_0 x) (F1_0 x)))
    (check-simplified? (((coordinate-system->inverse-metric R2-rect)
                         (coordinate-system->1form-basis R2-rect)
                         (coordinate-system->1form-basis R2-rect))
                        ((point R2-rect) (up 'x 'y)))
                       '(down (up (up (up 1 0) (up 0 1)) (up (up 0 0) (up 0 0)))
                              (up (up (up 0 0) (up 0 0)) (up (up 1 0) (up 0 1)))))
    (check-simplified? (((coordinate-system->inverse-metric R2-polar)
                         (coordinate-system->1form-basis R2-polar)
                         (coordinate-system->1form-basis R2-rect))
                        ((point R2-polar) (up 'r 'α)))
                       '(down (up (up (up (cos α) 0) (up 0 (/ (cos α) (expt r 2))))
                                  (up (up (sin α) 0) (up 0 (/ (sin α) (expt r 2)))))
                              (up (up (up (* -1 r (sin α)) 0) (up 0 (/ (* -1 (sin α)) r)))
                                  (up (up (* r (cos α)) 0) (up 0 (/ (cos α) r)))))))
   (test-case
    "literal-metric / make-metric"
    (define M12 ((make-metric 'M R3-spherical) 1 2))
    (check-equal? (expression M12) 'M_12)
    (check-equal? (expression (M12 ((point R3-spherical) #(x y z)))) '(M_12 (up x y z)))
    (define M (literal-metric 'M R2-rect))
    (check-equal? (argument-types M) (list vector-field? vector-field?))
    (check-simplified? ((M (literal-vector-field 'V1 R2-rect)
                           (literal-vector-field 'V2 R2-rect))
                        ((point R2-rect) #(x y)))
                       '(+ (* (+ (* (M_00 (up x y)) (V1^0 (up x y))) (* (M_01 (up x y)) (V1^1 (up x y)))) (V2^0 (up x y)))
                           (* (+ (* (M_01 (up x y)) (V1^0 (up x y))) (* (M_11 (up x y)) (V1^1 (up x y)))) (V2^1 (up x y))))))
   (test-case
    "components<->metric"
    (define basis (R2-polar 'coordinate-basis))
    (check-simplified? (((components->metric (metric->components (literal-metric 'M R2-rect) basis) basis)
                         (literal-vector-field 'V1 R2-rect)
                         (literal-vector-field 'V2 R2-rect))
                        ((point R2-rect) #(x y)))
                       '(+ (* (+ (* (M_00 (up x y)) (V1^0 (up x y))) (* (M_01 (up x y)) (V1^1 (up x y)))) (V2^0 (up x y)))
                           (* (+ (* (M_01 (up x y)) (V1^0 (up x y))) (* (M_11 (up x y)) (V1^1 (up x y)))) (V2^1 (up x y)))))
    (check-simplified? ((metric->components (literal-metric 'M R2-rect) (R2-polar 'coordinate-basis))
                        ((point R2-rect) #(x y)))
                       '(down
                         (down
                          (/ (+ (* (expt x 2) (M_00 (up x y))) (* 2 x y (M_01 (up x y))) (* (expt y 2) (M_11 (up x y)))) (+ (expt x 2) (expt y 2)))
                          (/ (+ (* (expt x 2) (M_01 (up x y))) (* -1 x y (M_00 (up x y))) (* x y (M_11 (up x y))) (* -1 (expt y 2) (M_01 (up x y)))) (sqrt (+ (expt x 2) (expt y 2)))))
                         (down
                          (/ (+ (* (expt x 2) (M_01 (up x y))) (* -1 x y (M_00 (up x y))) (* x y (M_11 (up x y))) (* -1 (expt y 2) (M_01 (up x y)))) (sqrt (+ (expt x 2) (expt y 2))))
                          (+ (* (expt x 2) (M_11 (up x y))) (* -2 x y (M_01 (up x y))) (* (expt y 2) (M_00 (up x y)))))))
    (check-simplified? ((metric->inverse-components (literal-metric 'M R2-rect) (R2-rect 'coordinate-basis))
                        ((point R2-rect) #(x y)))
                       '(up (up (/ (M_11 (up x y)) (+ (* (M_00 (up x y)) (M_11 (up x y))) (* -1 (expt (M_01 (up x y)) 2)))) (/ (* -1 (M_01 (up x y))) (+ (* (M_00 (up x y)) (M_11 (up x y))) (* -1 (expt (M_01 (up x y)) 2)))))
                            (up (/ (* -1 (M_01 (up x y))) (+ (* (M_00 (up x y)) (M_11 (up x y))) (* -1 (expt (M_01 (up x y)) 2)))) (/ (M_00 (up x y)) (+ (* (M_00 (up x y)) (M_11 (up x y))) (* -1 (expt (M_01 (up x y)) 2))))))))
   (test-case
    "metric:invert"
    (check-simplified? (((metric:invert (literal-metric 'M R2-rect) (R2-rect 'coordinate-basis))
                         (literal-1form-field 'F1 R2-rect)
                         (literal-1form-field 'F2 R2-rect))
                        ((point R2-rect) #(x y)))
                       '(/ (+ (* (M_00 (up x y)) (F2_1 (up x y)) (F1_1 (up x y))) (* -1 (M_01 (up x y)) (F2_1 (up x y)) (F1_0 (up x y)))
                              (* -1 (M_01 (up x y)) (F1_1 (up x y)) (F2_0 (up x y))) (* (M_11 (up x y)) (F1_0 (up x y)) (F2_0 (up x y))))
                           (+ (* (M_00 (up x y)) (M_11 (up x y))) (* -1 (expt (M_01 (up x y)) 2)))))
    (check-equal? (argument-types (metric:invert (literal-metric 'M R2-rect) (R2-rect 'coordinate-basis)))
                  (list 1form-field? 1form-field?)))
   (test-case
    "metric-over-map"
    (skip ;; TODO -- g should be on M but I only manage to get it working with R3 (N)
     )
    (define (g-on-M vf1 vf2) ((+ vf1 vf2) (literal-manifold-function 'mf R3-rect)))
    (define MM (metric-over-map (literal-manifold-map 'µNM R3-rect R2-polar) g-on-M))
    (define Vµ (MM (literal-vector-field 'V1 R3-rect) (literal-vector-field 'V2 R3-rect)))
    (check-simplified? (Vµ ((point R3-rect) #(x y z)))
                       '(+ (* (V1^0 (up x y z)) (((partial 0) mf) (up x y z)))
                           (* (V2^0 (up x y z)) (((partial 0) mf) (up x y z)))
                           (* (V1^1 (up x y z)) (((partial 1) mf) (up x y z)))
                           (* (V2^1 (up x y z)) (((partial 1) mf) (up x y z)))
                           (* (V1^2 (up x y z)) (((partial 2) mf) (up x y z)))
                           (* (V2^2 (up x y z)) (((partial 2) mf) (up x y z)))))
    (check-equal? (argument-types MM) (list vector-field? vector-field?)))
   (test-case
    "drop1 / raise1"
    ;; tensor 0,1 <-> 1,0 : covector <-> vector : down <-> up
    ;; raise is n,m -> n+1,m-1
    (define dropped ((drop1 (literal-metric 'M R2-rect)) (literal-vector-field 'vf1 R2-rect)))
    (check-true (operator? dropped))
    (check-true (1form-field? dropped))
    (check-equal? (expression (operator-name dropped)) '(lower vf1 M))
    (check-simplified? ((dropped (literal-vector-field 'vf2 R2-rect)) ((point R2-rect) #(x y)))
                       '(+ (* (+ (* (M_00 #(x y)) (vf2^0 #(x y))) (* (M_01 #(x y)) (vf2^1 #(x y)))) (vf1^0 #(x y)))
                           (* (+ (* (M_01 #(x y)) (vf2^0 #(x y))) (* (M_11 #(x y)) (vf2^1 #(x y)))) (vf1^1 #(x y)))))
    (define raised ((raise1 (literal-metric 'M R2-rect) (R2-rect 'coordinate-basis)) (literal-1form-field 'ff1 R2-rect)))
    (check-true (operator? raised))
    (check-true (vector-field? raised))
    (check-equal? (expression (operator-name raised)) '(raise ff1 M))
    (check-simplified? ((raised (compose (literal-function 'fct (-> (UP Real Real) Real)) (R2-rect '->coords)))
             ((point R2-rect) #(x y)))
                       '(/ (+ (* (M_00 (up x y)) (((partial 1) fct) (up x y)) (ff1_1 (up x y)))
                              (* -1 (M_01 (up x y)) (((partial 1) fct) (up x y)) (ff1_0 (up x y)))
                              (* -1 (M_01 (up x y)) (ff1_1 (up x y)) (((partial 0) fct) (up x y)))
                              (* (M_11 (up x y)) (ff1_0 (up x y)) (((partial 0) fct) (up x y))))
                           (+ (* (M_00 (up x y)) (M_11 (up x y))) (* -1 (expt (M_01 (up x y)) 2))))))
   (test-case
    "drop2 / raise2"
    (suppress-arguments '((up xx yy)))
    ;; tensor 0,2 <-> 2,0 : bilinear form <-> bivector : down <-> up
    (define basis (R2-rect 'coordinate-basis))
    (define (20T X Y)
      (define V (literal-vector-field 'vf3 R2-rect))
      (+ (X V) (Y V)))
    (define dropped ((drop2 (literal-metric 'M R2-rect) basis) 20T))
    (check-equal? (argument-types dropped) (list vector-field? vector-field?))
    (check-simplified? ((dropped (literal-vector-field 'vf1 R2-rect)
                                 (literal-vector-field 'vf2 R2-rect))
                        ((point R2-rect) #(xx yy)))
                       '(+ (* (+ (* M_00 vf1^0) (* M_01 vf1^1)) (+ vf3^0 vf3^0) (+ (* M_00 vf2^0) (* M_01 vf2^1)))
                           (* (+ (* M_00 vf1^0) (* M_01 vf1^1)) (+ vf3^0 vf3^1) (+ (* M_01 vf2^0) (* M_11 vf2^1)))
                           (* (+ (* M_01 vf1^0) (* M_11 vf1^1)) (+ vf3^1 vf3^0) (+ (* M_00 vf2^0) (* M_01 vf2^1)))
                           (* (+ (* M_01 vf1^0) (* M_11 vf1^1)) (+ vf3^1 vf3^1) (+ (* M_01 vf2^0) (* M_11 vf2^1)))))

    (define (02T vf1 vf2)
      (define h (compose (literal-function 'h (-> (UP Real Real) Real)) (R2-rect '->coords)))
      (+ (vf1 h) (vf2 h)))
    (define raised ((raise2 (literal-metric 'M R2-rect) basis) 02T))
    (check-equal? (argument-types raised) (list 1form-field? 1form-field?))
    (check-simplified? ((raised (literal-1form-field 'ff1 R2-rect) (literal-1form-field 'ff2 R2-rect))
                        ((point R2-rect) #(xx yy)))
                       '(+ (* (+ (/ (* M_11 ff1_0) (- (* M_00 M_11) (* M_01 M_01))) (/ (* M_01 ff1_1) (- (- (* M_00 M_11) (* M_01 M_01)))))
                              (+ ((partial 0) h) ((partial 0) h))
                              (+ (/ (* M_11 ff2_0) (- (* M_00 M_11) (* M_01 M_01))) (/ (* M_01 ff2_1) (- (- (* M_00 M_11) (* M_01 M_01))))))
                           (* (+ (/ (* M_11 ff1_0) (- (* M_00 M_11) (* M_01 M_01))) (/ (* M_01 ff1_1) (- (- (* M_00 M_11) (* M_01 M_01)))))
                              (+ ((partial 0) h) ((partial 1) h))
                              (+ (/ (* M_01 ff2_0) (- (- (* M_00 M_11) (* M_01 M_01)))) (/ (* M_00 ff2_1) (- (* M_00 M_11) (* M_01 M_01)))))
                           (* (+ (/ (* M_01 ff1_0) (- (- (* M_00 M_11) (* M_01 M_01)))) (/ (* M_00 ff1_1) (- (* M_00 M_11) (* M_01 M_01))))
                              (+ ((partial 1) h) ((partial 0) h))
                              (+ (/ (* M_11 ff2_0) (- (* M_00 M_11) (* M_01 M_01))) (/ (* M_01 ff2_1) (- (- (* M_00 M_11) (* M_01 M_01))))))
                           (* (+ (/ (* M_01 ff1_0) (- (- (* M_00 M_11) (* M_01 M_01)))) (/ (* M_00 ff1_1) (- (* M_00 M_11) (* M_01 M_01))))
                              (+ ((partial 1) h) ((partial 1) h))
                              (+ (/ (* M_01 ff2_0) (- (- (* M_00 M_11) (* M_01 M_01)))) (/ (* M_00 ff2_1) (- (* M_00 M_11) (* M_01 M_01)))))))
    (clear-arguments))
   (test-case
    "trace2down / up"
    (define basis (R2-rect 'coordinate-basis))
    (define (20T ff1 ff2)
      (define V (literal-vector-field 'h R2-rect))
      (+ (ff1 V) (ff2 V)))
    (define (02T vf1 vf2)
      (define h (compose (literal-function 'h (-> (UP Real Real) Real)) (R2-rect '->coords)))
      (+ (vf1 h) (vf2 h)))
    (define t2d ((trace2down (literal-metric 'M R2-rect) basis) 02T))
    (check-equal? (argument-types t2d) (list function?))
    (check-simplified? (t2d ((point R2-rect) #(x y)))
                       '(/ (+ (* 2 (M_00 (up x y)) (((partial 1) h) (up x y)))
                              (* -2 (M_01 (up x y)) (((partial 1) h) (up x y)))
                              (* -2 (M_01 (up x y)) (((partial 0) h) (up x y)))
                              (* 2 (M_11 (up x y)) (((partial 0) h) (up x y))))
                           (+ (* (M_00 (up x y)) (M_11 (up x y))) (* -1 (expt (M_01 (up x y)) 2)))))
    (define t2u ((trace2up (literal-metric 'M R2-rect) basis) 20T))
    (check-equal? (argument-types t2u) (list function?))
    (check-simplified? (t2u
                        ((point R2-rect) #(x y)))
                       '(+ (* 2 (M_00 (up x y)) (h^0 (up x y)))
                           (* 2 (M_01 (up x y)) (h^0 (up x y)))
                           (* 2 (M_01 (up x y)) (h^1 (up x y)))
                           (* 2 (M_11 (up x y)) (h^1 (up x y)))))
    (check-equal? (argument-types ((trace2up (literal-metric 'M R2-rect) basis) 20T))
                  (list function?)))
   (test-case
    "sharpen"
    (check-simplified? ((((sharpen (literal-metric 'M R2-rect) (R2-rect 'coordinate-basis) ((point R2-rect) #(x y)))
                          (literal-1form-field 'ff1 R2-rect))
                         (compose (literal-function 'w (-> (UP Real Real) Real)) (R2-rect '->coords)))
                        ((point R2-rect) #(v w)))
                       '(/ (+ (* (M_00 (up x y)) (ff1_1 (up x y)) (((partial 1) w) (up v w)))
                              (* -1 (M_01 (up x y)) (ff1_1 (up x y)) (((partial 0) w) (up v w)))
                              (* -1 (M_01 (up x y)) (ff1_0 (up x y)) (((partial 1) w) (up v w)))
                              (* (M_11 (up x y)) (ff1_0 (up x y)) (((partial 0) w) (up v w))))
                           (+ (* (M_00 (up x y)) (M_11 (up x y))) (* -1 (expt (M_01 (up x y)) 2))))))
   (test-case
    "S2-metric"
    (check-equal? (argument-types S2-metric) (list vector-field? vector-field?))
    (check-simplified? ((S2-metric (literal-vector-field 'vf1 S2-spherical)
                                   (literal-vector-field 'vf2 S2-spherical))
                        ((point S2-spherical) #(r p)))
                       '(+ (* (vf1^0 (up r p)) (vf2^0 (up r p))) (* (expt (sin r) 2) (vf1^1 (up r p)) (vf2^1 (up r p))))))
   (test-case
    "Example: natural metric on a sphere of radius R"
    (define 2-sphere R2-rect)
    (define-coordinates (up theta phi) 2-sphere)
    (define ((g-sphere R) u v)
      (* (square R)
         (+ (* (dtheta u) (dtheta v))
            (* (compose (square sin) theta)
               (dphi u)
               (dphi v)))))

    (define u (literal-vector-field 'u 2-sphere))
    (define v (literal-vector-field 'v 2-sphere))
    (check-simplified? (((g-sphere 'R) u v)
                        ((2-sphere '->point) (up 'theta0 'phi0)))
                       '(* (+ (* (v^0 (up theta0 phi0))
                                 (u^0 (up theta0 phi0)))
                              (* (expt (sin theta0) 2)
                                 (v^1 (up theta0 phi0))
                                 (u^1 (up theta0 phi0))))
                           (expt R 2))))
   (test-case
    "Example: Lorentz metric on R^4"
    (define SR R4-rect)
    (define-coordinates (up t x y z) SR)
    (define ((g-Lorentz c) u v)
      (+ (* (dx u) (dx v))
         (* (dy u) (dy v))
         (* (dz u) (dz v))
         (* -1 (square c) (dt u) (dt v))))
    (void "no actual test ..."))
   (test-case
    "Example: general metric on R^2"
    (define-coordinates (up x y) R2-rect)
    (define R2-basis (coordinate-system->basis R2-rect))
    (define ((g-R2 g_00 g_01 g_11) u v)
      (+ (* g_00 (dx u) (dx v))
         (* g_01 (+ (* (dx u) (dy v)) (* (dy u) (dx v))))
         (* g_11 (dy u) (dy v))))
    (check-simplified? (((g-R2 'a 'b 'c)
                         (literal-vector-field 'u R2-rect)
                         (literal-vector-field 'v R2-rect))
                        ((R2-rect '->point) (up 'x0 'y0)))
                       '(+ (* (u^0 (up x0 y0)) (v^0 (up x0 y0)) a)
                           (* (+ (* (v^0 (up x0 y0)) (u^1 (up x0 y0)))
                                 (* (u^0 (up x0 y0)) (v^1 (up x0 y0))))
                              b)
                           (* (v^1 (up x0 y0)) (u^1 (up x0 y0)) c))))
   (check-simplified? ((coordinate-system->metric-components R3-spherical) (up 'r 'theta 'phi))
                      '(down (down 1 0 0)
                             (down 0 (expt r 2) 0)
                             (down 0 0 (* (expt r 2) (expt (sin theta) 2)))))
   (check-simplified? (s:map/r (lambda (v1)
                                 (s:map/r (lambda (v2)
                                            (((coordinate-system->metric R3-spherical) v1 v2)
                                             ((point R3-spherical) (up 'r 'theta 'phi))))
                                          (coordinate-system->vector-basis R3-spherical)))
                               (coordinate-system->vector-basis R3-spherical))
                      '(down (down 1 0 0)
                             (down 0 (expt r 2) 0)
                             (down 0 0 (* (expt r 2) (expt (sin theta) 2)))))
   (check-simplified? (s:map/r (lambda (w1)
                                 (s:map/r (lambda (w2)
                                            (((coordinate-system->inverse-metric R3-spherical) w1 w2)
                                             ((point R3-spherical) (up 'r 'theta 'phi))))
                                          (coordinate-system->1form-basis R3-spherical)))
                               (coordinate-system->1form-basis R3-spherical))
                      '(up (up 1 0 0)
                           (up 0 (/ 1 (expt r 2)) 0)
                           (up 0 0 (/ 1 (* (expt r 2) (expt (sin theta) 2))))))
   (check-simplified? (((literal-metric 'g R3-rect)
                        (literal-vector-field 'u R3-rect)
                        (literal-vector-field 'v R3-rect))
                       ((R3-rect '->point) (up 'x0 'y0 'z0)))
                      '(+ (* (v^0 (up x0 y0 z0)) (u^0 (up x0 y0 z0)) (g_00 (up x0 y0 z0)))
                          (* (v^0 (up x0 y0 z0)) (g_01 (up x0 y0 z0)) (u^1 (up x0 y0 z0)))
                          (* (v^0 (up x0 y0 z0)) (g_02 (up x0 y0 z0)) (u^2 (up x0 y0 z0)))
                          (* (u^0 (up x0 y0 z0)) (v^1 (up x0 y0 z0)) (g_01 (up x0 y0 z0)))
                          (* (u^0 (up x0 y0 z0)) (v^2 (up x0 y0 z0)) (g_02 (up x0 y0 z0)))
                          (* (v^1 (up x0 y0 z0)) (u^1 (up x0 y0 z0)) (g_11 (up x0 y0 z0)))
                          (* (v^1 (up x0 y0 z0)) (g_12 (up x0 y0 z0)) (u^2 (up x0 y0 z0)))
                          (* (v^2 (up x0 y0 z0)) (u^1 (up x0 y0 z0)) (g_12 (up x0 y0 z0)))
                          (* (v^2 (up x0 y0 z0)) (u^2 (up x0 y0 z0)) (g_22 (up x0 y0 z0)))))
   (test-case
    ""
    (define-coordinates (up x y) R2-rect)
    (define R2-basis (coordinate-system->basis R2-rect))
    (define ((g-R2 g_00 g_01 g_11) u v)
      (+ (* g_00 (dx u) (dx v))
         (* g_01 (+ (* (dx u) (dy v)) (* (dy u) (dx v))))
         (* g_11 (dy u) (dy v))))
    (check-simplified? (((metric:invert (g-R2 'a 'b 'c) R2-basis)
                         (literal-1form-field 'omega R2-rect)
                         (literal-1form-field 'theta R2-rect))
                        ((R2-rect '->point) (up 'x0 'y0)))
                       '(/ (+ (* a (theta_1 (up x0 y0)) (omega_1 (up x0 y0)))
                              (* -1 b (theta_1 (up x0 y0)) (omega_0 (up x0 y0)))
                              (* -1 b (omega_1 (up x0 y0)) (theta_0 (up x0 y0)))
                              (* c (omega_0 (up x0 y0)) (theta_0 (up x0 y0))))
                           (+ (* a c) (* -1 (expt b 2)))))
    ;;; Test of inversion
    (check-simplified? (let* ((g (g-R2 'a 'b 'c))
                              (gi (metric:invert g R2-basis))
                              (vector-basis (list d/dx d/dy))
                              (dual-basis (list dx dy))
                              (m ((R2-rect '->point) (up 'x0 'y0))))
                         (matrix:generate 2 2
                                          (lambda (i k)
                                            (sigma (lambda (j)
                                                     (* ((gi (ref dual-basis i) (ref dual-basis j)) m)
                                                        ((g  (ref vector-basis j) (ref vector-basis k)) m)))
                                                   0 1))))
                       '(matrix-by-rows (list 1 0) (list 0 1)))
    (check-simplified? ((((lower (g-R2 'a 'b 'c))
                          (literal-vector-field 'v R2-rect))
                         (literal-vector-field 'w R2-rect))
                        ((R2-rect '->point) (up 'x0 'y0)))
                       '(+ (* a (v^0 (up x0 y0)) (w^0 (up x0 y0)))
                           (* b (v^0 (up x0 y0)) (w^1 (up x0 y0)))
                           (* b (v^1 (up x0 y0)) (w^0 (up x0 y0)))
                           (* c (v^1 (up x0 y0)) (w^1 (up x0 y0)))))
    (check-simplified? ((((raise (g-R2 'a 'b 'c) R2-basis)
                          ((lower (g-R2 'a 'b 'c)) (literal-vector-field 'v R2-rect)))
                         (compose (literal-function 'w (-> (UP Real Real) Real))
                                  (R2-rect '->coords)))
                        ((R2-rect '->point) (up 'x0 'y0)))
                       '(+ (* (v^0 (up x0 y0)) (((partial 0) w) (up x0 y0)))
                           (* (v^1 (up x0 y0)) (((partial 1) w) (up x0 y0)))))
    (check-simplified? ((((sharpen (g-R2 'a 'b 'c) R2-basis ((R2-rect '->point) (up 'x0 'y0)))
                          ((lower (g-R2 'a 'b 'c)) (literal-vector-field 'v R2-rect)))
                         (compose (literal-function 'w (-> (UP Real Real) Real))
                                  (R2-rect '->coords)))
                        ((R2-rect '->point) (up 'x0 'y0)))
                       '(+ (* (v^0 (up x0 y0)) (((partial 0) w) (up x0 y0)))
                           (* (v^1 (up x0 y0)) (((partial 1) w) (up x0 y0))))))
   ))

(module+ test
  (require rackunit/text-ui)
  (run-tests the-tests))