#lang racket/base

(require rackunit
         "../../main.rkt"
         "../helper+scm.rkt"
         )

(provide the-tests)
(define the-tests
  (test-suite
   "calculus/vector-calculus"
   (test-case
    "gradient 3D"
    ;; same as Test 'spherical system' below but via R3-spherical instead of R3-rect
    (define spherical R3-spherical)
    (define-coordinates (up r theta phi) spherical)
    (define spherical-point ((point spherical) (up 'r 'theta 'phi)))
    (define spherical-basis (coordinate-system->basis spherical))
    (define (spherical-metric v1 v2)
      (+ (* (dr v1) (dr v2))
         (* (square r)
            (+ (* (dtheta v1) (dtheta v2))
               (* (expt (sin theta) 2)
                  (dphi v1) (dphi v2))))))
    (check-simplified? (((basis->1form-basis spherical-basis)
                         ((gradient spherical-metric spherical-basis)
                          (literal-manifold-function 'f spherical)))
                        spherical-point)
                       '(up (((partial 0) f) (up r theta phi))
                            (/ (((partial 1) f) (up r theta phi)) (expt r 2))
                            (/ (((partial 2) f) (up r theta phi)) (* (expt r 2) (expt (sin theta) 2))))))
   (test-case
    "gradient 2D"
    (define polar R2-polar)
    (define-coordinates (up r theta) polar)
    (define polar-point ((point polar) (up 'r 'theta)))
    (define polar-basis (coordinate-system->basis polar))
    (define (polar-metric v1 v2)
      (+ (* (dr v1) (dr v2))
         (* (square r) (* (dtheta v1) (dtheta v2)))))
    (check-simplified? (((basis->1form-basis polar-basis)
                         ((gradient polar-metric polar-basis)
                          (literal-manifold-function 'f polar)))
                        polar-point)
                       '(up (((partial 0) f) (up r theta))
                            (/ (((partial 1) f) (up r theta)) (expt r 2)))))
   (test-case
    "curl"
    ;; rot - ∇× - only on 3D space ...? TODO: should not be necessary for differential forms
    (define spherical R3-spherical)
    (define-coordinates (up r theta phi) spherical)
    (define spherical-point ((point spherical) (up 'r 'theta 'phi)))
    (define spherical-basis (coordinate-system->basis spherical))
    (define (spherical-metric v1 v2)
      (+ (* (dr v1) (dr v2))
         (* (square r)
            (+ (* (dtheta v1) (dtheta v2))
               (* (expt (sin theta) 2)
                  (dphi v1) (dphi v2))))))
    (check-simplified? (((basis->1form-basis spherical-basis)
                         ((curl spherical-metric spherical-basis)
                          (literal-vector-field 'v R3-spherical)))
                        spherical-point)
                       '(up (+ (* 2 (expt r 6) (expt (sin theta) 3) (cos theta) (v^2 (up r theta phi)))
                               (* (expt r 6) (expt (cos theta) 4) (((partial 1) v^2) (up r theta phi)))
                               (* -1 (expt r 6) (expt (sin theta) 2) (((partial 2) v^1) (up r theta phi)))
                               (* -2 (expt r 6) (expt (cos theta) 2) (((partial 1) v^2) (up r theta phi)))
                               (* (expt r 6) (((partial 1) v^2) (up r theta phi))))
                            (+ (* -1 (expt r 2) (expt (cos theta) 4) (((partial 0) v^2) (up r theta phi)))
                               (* -2 r (expt (cos theta) 4) (v^2 (up r theta phi)))
                               (* 2 (expt r 2) (expt (cos theta) 2) (((partial 0) v^2) (up r theta phi)))
                               (* 4 r (expt (cos theta) 2) (v^2 (up r theta phi)))
                               (* -1 (expt r 2) (((partial 0) v^2) (up r theta phi)))
                               (* (expt (sin theta) 2) (((partial 2) v^0) (up r theta phi)))
                               (* -2 r (v^2 (up r theta phi))))
                            (/ (+
                                (* (expt r 2) (((partial 0) v^1) (up r theta phi)))
                                (* 2 r (v^1 (up r theta phi)))
                                (* -1 (((partial 1) v^0) (up r theta phi))))
                               (expt (sin theta) 2)))))
   (test-case
    "divergence"
    (define spherical R3-spherical)
    (define-coordinates (up r theta phi) spherical)
    (define spherical-point ((point spherical) (up 'r 'theta 'phi)))
    (define spherical-basis (coordinate-system->basis spherical))
    (define (spherical-metric v1 v2)
      (+ (* (dr v1) (dr v2))
         (* (square r)
            (+ (* (dtheta v1) (dtheta v2))
               (* (expt (sin theta) 2)
                  (dphi v1) (dphi v2))))))
    (check-simplified? (((divergence spherical-metric spherical-basis)
                         (literal-vector-field 'v R3-spherical))
                        spherical-point)
                       '(+ (* -1 (expt r 8) (expt (cos theta) 6) (((partial 2) v^2) (up r theta phi)))
                           (* -3 (expt r 8) (expt (sin theta) 2) (expt (cos theta) 2) (((partial 2) v^2) (up r theta phi)))
                           (* (expt r 8) (expt (sin theta) 2) (((partial 1) v^1) (up r theta phi)))
                           (* (expt r 8) (((partial 2) v^2) (up r theta phi)))
                           (* (expt r 4) (expt (sin theta) 2) (((partial 0) v^0) (up r theta phi))))))
   (test-case
    "divergence"
    (define polar R2-polar)
    (define-coordinates (up r theta) polar)
    (define polar-point ((point polar) (up 'r 'theta)))
    (define polar-basis (coordinate-system->basis polar))
    (define (polar-metric v1 v2)
      (+ (* (dr v1) (dr v2))
         (* (square r) (* (dtheta v1) (dtheta v2)))))
    (check-simplified? (((divergence polar-metric polar-basis)
                         (literal-vector-field 'v R2-polar))
                        polar-point)
                       '(+ (* (expt r 6) (((partial 1) v^1) (up r theta)))
                           (* (expt r 2) (((partial 0) v^0) (up r theta))))))
   (test-case
    "Laplacian"
    (define polar R2-polar)
    (define-coordinates (up r theta) polar)
    (define polar-point ((point polar) (up 'r 'theta)))
    (define polar-basis (coordinate-system->basis polar))
    (define (polar-metric v1 v2)
      (+ (* (dr v1) (dr v2))
         (* (square r) (* (dtheta v1) (dtheta v2)))))
    (check-simplified? (((Laplacian polar-metric polar-basis)
                         ;; should use here r or theta
                         (λ (p) (define c ((R2-rect '->coords) p))
                           (+ (ref c 0) (ref c 1))))
                        polar-point)
                       '(+ (* -1 (expt r 5) (sin theta)) (* -1 (expt r 5) (cos theta)))))
   (test-case
    "coordinate-system->Lame-coefficients"
    (define (check-Lamé CS rslt)
      (check-simplified? ((coordinate-system->Lame-coefficients CS) (CS 'coordinate-prototype))
                         rslt))
    (check-Lamé R1-rect (down 1))
    (check-Lamé R2-rect (down 1 1))
    (check-Lamé R2-polar (down 1 'r))
    (check-Lamé R3-rect (down 1 1 1))
    (check-Lamé R3-cyl (down 1 'x0 1))
    (check-Lamé R3-spherical (down 1 'r (* 'r (sin 'theta))))
    (check-Lamé R4-rect (down 1 1 1 1))
    (check-Lamé R4-cyl (down 1 'x0 1 1))
    (check-Lamé spacetime-rect (down 1 1 1 1))
    (check-Lamé spacetime-sphere (down 1 1 'x1 (* 'x1 (sin 'x2))))

    (check-Lamé S1-circular (down 1))
    (check-Lamé S1-slope (down (/ 2 (+ 1 (expt 'x0 2)))))
    (check-Lamé S1-gnomic (down (/ 1 (+ 1 (expt 'x0 2)))))
    (check-Lamé S2-spherical (down 1 (sin 'x0)))
    (check-Lamé S2-tilted (down 1 (sin 'x0)))
    (check-Lamé S2-stereographic (down (/ 2 (+ 1 (expt 'x0 2) (expt 'x1 2)))
                                       (/ 2 (+ 1 (expt 'x0 2) (expt 'x1 2)))))

    (define 2gnom
      (let ([x0 'x0][x1 'x1])
        (down (/ (sqrt (+ 1 (* (expt x0 2) (expt x1 2)) (expt x1 4) (expt x0 2) (* 2 (expt x1 2))))
                 (+ (* (expt x0 2) (sqrt (+ 1 (expt x0 2) (expt x1 2))))
                    (* (expt x1 2) (sqrt (+ 1 (expt x0 2) (expt x1 2))))
                    (sqrt (+ 1 (expt x0 2) (expt x1 2)))))
              (/ (sqrt (+ 1 (expt x0 4) (* (expt x0 2) (expt x1 2)) (* 2 (expt x0 2)) (expt x1 2)))
                 (+ (* (expt x0 2) (sqrt (+ 1 (expt x0 2) (expt x1 2))))
                    (* (expt x1 2) (sqrt (+ 1 (expt x0 2) (expt x1 2))))
                    (sqrt (+ 1 (expt x0 2) (expt x1 2))))))))
    (check-Lamé S2-gnomic 2gnom)
    (check-Lamé S2p-spherical (down 1 (sin 'x0)))
    (check-Lamé S2p-tilted    (down 1 (sin 'x0)))
    (check-Lamé S2p-stereographic (down (/ 2 (+ 1 (expt 'x0 2) (expt 'x1 2)))
                                        (/ 2 (+ 1 (expt 'x0 2) (expt 'x1 2)))))
    (check-Lamé S2p-gnomic 2gnom)
    (check-Lamé S3-spherical (down 1 (sin 'x0) (* (sin 'x1) (sin 'x0))))
    (check-Lamé S3-tilted    (down 1 (sin 'x0) (* (sin 'x1) (sin 'x0))))
    (check-Lamé S3-gnomic
                (let ([x0 'x0][x1 'x1][x2 'x2])
                  (let ([√1+... (sqrt (+ 1 (expt x0 2) (expt x1 2) (expt x2 2)))])
                    (down (/ (sqrt (+ 1 (* (expt x0 2) (expt x1 2)) (* (expt x0 2) (expt x2 2)) (expt x1 4) (* 2 (expt x1 2) (expt x2 2)) (expt x2 4) (expt x0 2) (* 2 (expt x1 2)) (* 2 (expt x2 2))))
                             (+ (* (expt x0 2) √1+...) (* (expt x1 2) √1+...) (* (expt x2 2) √1+...) √1+...))
                        (/ (sqrt (+ 1 (expt x0 4) (* (expt x0 2) (expt x1 2)) (* 2 (expt x0 2) (expt x2 2)) (* (expt x1 2) (expt x2 2)) (expt x2 4) (* 2 (expt x0 2)) (expt x1 2) (* 2 (expt x2 2))))
                           (+ (* (expt x0 2) √1+...) (* (expt x1 2) √1+...) (* (expt x2 2) √1+...) √1+...))
                        (/ (sqrt (+ 1 (expt x0 4) (* 2 (expt x0 2) (expt x1 2)) (* (expt x0 2) (expt x2 2)) (expt x1 4) (* (expt x1 2) (expt x2 2)) (* 2 (expt x0 2)) (* 2 (expt x1 2)) (expt x2 2)))
                           (+ (* (expt x0 2) √1+...) (* (expt x1 2) √1+...) (* (expt x2 2) √1+...) √1+...))))))
    (check-Lamé S3-stereographic (down (/ 2 (+ 1 (expt 'x0 2) (expt 'x1 2) (expt 'x2 2)))
                                       (/ 2 (+ 1 (expt 'x0 2) (expt 'x1 2) (expt 'x2 2)))
                                       (/ 2 (+ 1 (expt 'x0 2) (expt 'x1 2) (expt 'x2 2)))))
    (check-Lamé Euler-angles     '(down (sqrt 2) (sqrt 2) (sqrt 2)))
    (check-Lamé alternate-angles '(down (sqrt 2) (sqrt 2) (sqrt 2))))
   (test-case
    "coordinate-system->orthonormal-vector-basis"
    (define (check-ortho CS rslt)
      (check-simplified? (((coordinate-system->orthonormal-vector-basis CS)
                           (literal-manifold-function 'f CS))
                          ((point CS) (CS 'coordinate-prototype)))
                         rslt))
    (skip ;; TODO -- mixing 1D 'x and (up 'x) causes problems!
     (check-ortho R1-rect '(down ((derivative f) x0)))
     (check-ortho S1-circular (down 1))
     (check-ortho S1-slope (down (/ 2 (+ 1 (expt 'x0 2)))))
     (check-ortho S1-gnomic (down (/ 1 (+ 1 (expt 'x0 2))))))

    (check-ortho R2-rect '(down (((partial 0) f) (up x0 x1))
                                (((partial 1) f) (up x0 x1))))
    (check-ortho R2-polar '(down (((partial 0) f) (up r theta))
                                 (/ (((partial 1) f) (up r theta)) r)))
    (check-ortho R3-rect '(down (((partial 0) f) (up x0 x1 x2))
                                (((partial 1) f) (up x0 x1 x2))
                                (((partial 2) f) (up x0 x1 x2))))
    (check-ortho R3-cyl '(down (((partial 0) f) (up x0 x1 x2))
                               (/ (((partial 1) f) (up x0 x1 x2)) x0)
                               (((partial 2) f) (up x0 x1 x2))))
    (check-ortho R3-spherical '(down (((partial 0) f) (up r theta phi))
                                     (/ (((partial 1) f) (up r theta phi)) r)
                                     (/ (((partial 2) f) (up r theta phi)) (* r (sin theta)))))
    (check-ortho R4-rect '(down (((partial 0) f) (up x0 x1 x2 x3))
                                (((partial 1) f) (up x0 x1 x2 x3))
                                (((partial 2) f) (up x0 x1 x2 x3))
                                (((partial 3) f) (up x0 x1 x2 x3))))
    (check-ortho R4-cyl '(down (((partial 0) f) (up x0 x1 x2 x3))
                               (/ (((partial 1) f) (up x0 x1 x2 x3)) x0)
                               (((partial 2) f) (up x0 x1 x2 x3))
                               (((partial 3) f) (up x0 x1 x2 x3))))
    (check-ortho spacetime-rect '(down (((partial 0) f) (up x0 x1 x2 x3))
                                       (((partial 1) f) (up x0 x1 x2 x3))
                                       (((partial 2) f) (up x0 x1 x2 x3))
                                       (((partial 3) f) (up x0 x1 x2 x3))))
    (check-ortho spacetime-sphere '(down (((partial 0) f) (up x0 x1 x2 x3))
                                         (((partial 1) f) (up x0 x1 x2 x3))
                                         (/ (((partial 2) f) (up x0 x1 x2 x3)) x1)
                                         (/ (((partial 3) f) (up x0 x1 x2 x3)) (* x1 (sin x2)))))

    (check-ortho S2-spherical '(down (((partial 0) f) (up x0 x1))
                                     (/ (((partial 1) f) (up x0 x1)) (sin x0))))
    (check-ortho S2-tilted '(down (((partial 0) f) (up x0 x1))
                                  (/ (((partial 1) f) (up x0 x1)) (sin x0))))
    ;; slow
    (check-ortho S2-stereographic '(down (+ (* 1/2 (expt x0 2) (((partial 0) f) (up x0 x1)))
                                            (* 1/2 (expt x1 2) (((partial 0) f) (up x0 x1)))
                                            (* x0 (f (up x0 x1)))
                                            (* 1/2 (((partial 0) f) (up x0 x1))))
                                         (+ (* 1/2 (expt x0 2) (((partial 1) f) (up x0 x1)))
                                            (* 1/2 (expt x1 2) (((partial 1) f) (up x0 x1)))
                                            (* x1 (f (up x0 x1)))
                                            (* 1/2 (((partial 1) f) (up x0 x1))))))

    (define 2gnom
      '(down (/ (+ (* (expt x0 2) (sqrt (+ 1 (expt x0 2) (expt x1 2))) (((partial 0) f) (up x0 x1)))
                   (* (expt x1 2) (sqrt (+ 1 (expt x0 2) (expt x1 2))) (((partial 0) f) (up x0 x1)))
                   (* 2 x0 (sqrt (+ 1 (expt x0 2) (expt x1 2))) (f (up x0 x1)))
                   (* (sqrt (+ 1 (expt x0 2) (expt x1 2))) (((partial 0) f) (up x0 x1))))
                (sqrt (+ 1 (* (expt x0 2) (expt x1 2)) (expt x1 4) (expt x0 2) (* 2 (expt x1 2)))))
             (/ (+ (* (expt x0 2) (sqrt (+ 1 (expt x0 2) (expt x1 2))) (((partial 1) f) (up x0 x1)))
                   (* (expt x1 2) (sqrt (+ 1 (expt x0 2) (expt x1 2))) (((partial 1) f) (up x0 x1)))
                   (* 2 x1 (sqrt (+ 1 (expt x0 2) (expt x1 2))) (f (up x0 x1)))
                   (* (sqrt (+ 1 (expt x0 2) (expt x1 2))) (((partial 1) f) (up x0 x1))))
                (sqrt (+ 1 (expt x0 4) (* (expt x0 2) (expt x1 2)) (* 2 (expt x0 2)) (expt x1 2))))))
    (check-ortho S2-gnomic 2gnom)
    (check-ortho S2p-spherical '(down (((partial 0) f) (up x0 x1))
                                      (/ (((partial 1) f) (up x0 x1)) (sin x0))))
    (check-ortho S2p-tilted    '(down (((partial 0) f) (up x0 x1))
                                      (/ (((partial 1) f) (up x0 x1)) (sin x0))))
    ;; slow
    (check-ortho S2p-stereographic '(down (+ (* 1/2 (expt x0 2) (((partial 0) f) (up x0 x1)))
                                             (* 1/2 (expt x1 2) (((partial 0) f) (up x0 x1)))
                                             (* x0 (f (up x0 x1)))
                                             (* 1/2 (((partial 0) f) (up x0 x1))))
                                          (+ (* 1/2 (expt x0 2) (((partial 1) f) (up x0 x1)))
                                             (* 1/2 (expt x1 2) (((partial 1) f) (up x0 x1)))
                                             (* x1 (f (up x0 x1)))
                                             (* 1/2 (((partial 1) f) (up x0 x1))))))
    (check-ortho S2p-gnomic 2gnom)

    ;; very-slow
    #;(check-ortho S3-spherical '(down (((partial 0) f) (up x0 x1 x2))
                                     (/ (((partial 1) f) (up x0 x1 x2)) (sin x0))
                                     (/ (((partial 2) f) (up x0 x1 x2)) (* (sin x1) (sin x0)))))
    ;; very-slow
    #;(check-ortho S3-tilted    '(down (((partial 0) f) (up x0 x1 x2))
                                     (/ (((partial 1) f) (up x0 x1 x2)) (sin x0))
                                     (/ (((partial 2) f) (up x0 x1 x2)) (* (sin x1) (sin x0)))))
    ;; slow
    (check-ortho S3-gnomic
                 (let ([√1+... '(sqrt (+ 1 (expt x0 2) (expt x1 2) (expt x2 2)))])
                   (define (partials n)
                     `(+ (* (expt x0 2) ,√1+... (((partial ,n) f) (up x0 x1 x2)))
                         (* (expt x1 2) ,√1+... (((partial ,n) f) (up x0 x1 x2)))
                         (* (expt x2 2) ,√1+... (((partial ,n) f) (up x0 x1 x2)))
                         (* 2 ,(string->symbol (format "x~a" n)) ,√1+... (f (up x0 x1 x2)))
                         (* ,√1+... (((partial ,n) f) (up x0 x1 x2)))))
                   `(down (/ ,(partials 0)
                             (sqrt (+ 1 (* (expt x0 2) (expt x1 2)) (* (expt x0 2) (expt x2 2)) (expt x1 4) (* 2 (expt x1 2) (expt x2 2)) (expt x2 4)
                                      (expt x0 2) (* 2 (expt x1 2)) (* 2 (expt x2 2)))))
                          (/ ,(partials 1)
                             (sqrt (+ 1 (expt x0 4) (* (expt x0 2) (expt x1 2)) (* 2 (expt x0 2) (expt x2 2)) (* (expt x1 2) (expt x2 2)) (expt x2 4)
                                      (* 2 (expt x0 2)) (expt x1 2) (* 2 (expt x2 2)))))
                          (/ ,(partials 2)
                             (sqrt (+ 1 (expt x0 4) (* 2 (expt x0 2) (expt x1 2)) (* (expt x0 2) (expt x2 2)) (expt x1 4) (* (expt x1 2) (expt x2 2))
                                      (* 2 (expt x0 2)) (* 2 (expt x1 2)) (expt x2 2)))))))
    ;; slower
    (check-ortho S3-stereographic '(down (+ (* 1/2 (expt x0 2) (((partial 0) f) (up x0 x1 x2)))
                                            (* 1/2 (expt x1 2) (((partial 0) f) (up x0 x1 x2)))
                                            (* 1/2 (expt x2 2) (((partial 0) f) (up x0 x1 x2)))
                                            (* x0 (f (up x0 x1 x2)))
                                            (* 1/2 (((partial 0) f) (up x0 x1 x2))))
                                         (+ (* 1/2 (expt x0 2) (((partial 1) f) (up x0 x1 x2)))
                                            (* 1/2 (expt x1 2) (((partial 1) f) (up x0 x1 x2)))
                                            (* 1/2 (expt x2 2) (((partial 1) f) (up x0 x1 x2)))
                                            (* x1 (f (up x0 x1 x2)))
                                            (* 1/2 (((partial 1) f) (up x0 x1 x2))))
                                         (+ (* 1/2 (expt x0 2) (((partial 2) f) (up x0 x1 x2)))
                                            (* 1/2 (expt x1 2) (((partial 2) f) (up x0 x1 x2)))
                                            (* 1/2 (expt x2 2) (((partial 2) f) (up x0 x1 x2)))
                                            (* x2 (f (up x0 x1 x2)))
                                            (* 1/2 (((partial 2) f) (up x0 x1 x2))))))
    (check-ortho Euler-angles     '(down (/ (((partial 0) f) (up x0 x1 x2)) (sqrt 2))
                                         (/ (((partial 1) f) (up x0 x1 x2)) (sqrt 2))
                                         (/ (((partial 2) f) (up x0 x1 x2)) (sqrt 2))))
    (check-ortho alternate-angles '(down (/ (((partial 0) f) (up x0 x1 x2)) (sqrt 2))
                                         (/ (((partial 1) f) (up x0 x1 x2)) (sqrt 2))
                                         (/ (((partial 2) f) (up x0 x1 x2)) (sqrt 2))))
    )
   (test-case
    "Test setup for spherical system"
    (define spherical R3-rect)
    (define-coordinates (up r theta phi) spherical)
    (define spherical-point
      ((point spherical) (up 'r 'theta 'phi)))
    (define spherical-basis
      (coordinate-system->basis spherical))
    (define (spherical-metric v1 v2)
      (+ (* (dr v1) (dr v2))
         (* (square r)
            (+ (* (dtheta v1) (dtheta v2))
               (* (expt (sin theta) 2)
                  (dphi v1) (dphi v2))))))
    (define spherical-Gamma
      (make-Christoffel
       (let ((O (lambda x 0)))
         (down
          (down (up O O O)
                (up O (/ 1 r) O)
                (up O O (/ 1 r)))
          (down (up O (/ 1 r) O)
                (up (* -1 r) O O)
                (up O O (/ (cos theta) (sin theta))))
          (down (up O O (/ 1 r))
                (up O O (/ (cos theta) (sin theta)))
                (up (* -1 r (expt (sin theta) 2))
                    (* -1 (sin theta) (cos theta))
                    O))))
       (coordinate-system->basis spherical)))
    (define spherical-Cartan
      (Christoffel->Cartan spherical-Gamma))
    ;;; normalized spherical basis
    (define e_0 d/dr)
    (define e_1 (* (/ 1 r) d/dtheta))
    (define e_2 (* (/ 1 (* r (sin theta))) d/dphi))
    (check-simplified? ((spherical-metric e_0 e_0) spherical-point) 1)
    (check-simplified? ((spherical-metric e_1 e_1) spherical-point) 1)
    (check-simplified? ((spherical-metric e_2 e_2) spherical-point) 1)
    (check-simplified? ((spherical-metric e_0 e_1) spherical-point) 0)
    (check-simplified? ((spherical-metric e_0 e_2) spherical-point) 0)
    (check-simplified? ((spherical-metric e_1 e_2) spherical-point) 0)
    (define orthonormal-spherical-vector-basis
      (down e_0 e_1 e_2))
    (define orthonormal-spherical-1form-basis
      (vector-basis->dual orthonormal-spherical-vector-basis
                          spherical))
    (define orthonormal-spherical-basis
      (make-basis orthonormal-spherical-vector-basis
                  orthonormal-spherical-1form-basis))
    (define v
      (+ (* (literal-manifold-function 'v^0 spherical) e_0)
         (* (literal-manifold-function 'v^1 spherical) e_1)
         (* (literal-manifold-function 'v^2 spherical) e_2)))
    ;;; Test of Gradient
    (check-simplified? ((orthonormal-spherical-1form-basis
                         ((gradient spherical-metric spherical-basis)
                          (literal-manifold-function 'f spherical)))
                        spherical-point)
                       '(up (((partial 0) f) (up r theta phi))
                            (/ (((partial 1) f) (up r theta phi)) r)
                            (/ (((partial 2) f) (up r theta phi)) (* r (sin theta)))))
    ;;; Test of Curl
    (check-simplified? ((orthonormal-spherical-1form-basis
                         ((curl spherical-metric orthonormal-spherical-basis) v))
                        spherical-point)
                       '(up
                         (/ (+ (* (sin theta) (((partial 1) v^2) (up r theta phi)))
                               (* (cos theta) (v^2 (up r theta phi)))
                               (* -1 (((partial 2) v^1) (up r theta phi))))
                            (* r (sin theta)))
                         (/ (+ (* -1 r (sin theta) (((partial 0) v^2) (up r theta phi)))
                               (* -1 (sin theta) (v^2 (up r theta phi)))
                               (((partial 2) v^0) (up r theta phi)))
                            (* r (sin theta)))
                         (/ (+ (* r (((partial 0) v^1) (up r theta phi)))
                               (v^1 (up r theta phi))
                               (* -1 (((partial 1) v^0) (up r theta phi))))
                            r)))
    ;;; Test of Divergence
    (check-simplified? (((divergence spherical-metric orthonormal-spherical-basis) v)
                        spherical-point)
                       '(+ (((partial 0) v^0) (up r theta phi))
                           (/ (* 2 (v^0 (up r theta phi))) r)
                           (/ (((partial 1) v^1) (up r theta phi)) r)
                           (/ (* (v^1 (up r theta phi)) (cos theta)) (* r (sin theta)))
                           (/ (((partial 2) v^2) (up r theta phi)) (* r (sin theta)))))
    (let ([phi (literal-manifold-function 'phi spherical)])
      (check-simplified? (((Laplacian spherical-metric orthonormal-spherical-basis)
                           phi)
                          spherical-point)
                         '(+ (((partial 0) ((partial 0) phi)) (up r theta phi))
                             (/ (* 2 (((partial 0) phi) (up r theta phi)))
                                r)
                             (/ (((partial 1) ((partial 1) phi)) (up r theta phi))
                                (expt r 2))
                             (/ (* (cos theta) (((partial 1) phi) (up r theta phi)))
                                (* (expt r 2) (sin theta)))
                             (/ (((partial 2) ((partial 2) phi)) (up r theta phi))
                                (* (expt r 2) (expt (sin theta) 2)))))))
   (test-case
    "R4-rect"
    ;;; Obtaining the wave equation.
    (define SR R4-rect)
    (define-coordinates (up t x y z) SR)
    (define an-event ((point SR) (up 't0 'x0 'y0 'z0)))
    (define c 'c)         ; We like units.
    (define (g-Minkowski u v)
      (+ (* -1 (square c) (dt u) (dt v))
         (* (dx u) (dx v))
         (* (dy u) (dy v))
         (* (dz u) (dz v))))
    (define SR-vector-basis
      (down (* (/ 1 c) d/dt) d/dx d/dy d/dz))
    (define SR-1form-basis
      (up (* c dt) dx dy dz))
    (define SR-basis
      (make-basis SR-vector-basis
                  SR-1form-basis))
    (check-simplified? (s:map/r
                        (lambda (u)
                          (s:map/r (lambda (v)
                                     ((g-Minkowski u v) an-event))
                                   SR-vector-basis))
                        SR-vector-basis)
                       '(down (down -1 0 0 0)
                              (down  0 1 0 0)
                              (down  0 0 1 0)
                              (down  0 0 0 1)))

    (let ([phi (literal-manifold-function 'phi SR)])
      (check-simplified? (((Laplacian g-Minkowski SR-basis) phi) an-event)
                         '(+ (* -1 (((partial 1) ((partial 1) phi)) (up t0 x0 y0 z0)))
                             (* -1 (((partial 2) ((partial 2) phi)) (up t0 x0 y0 z0)))
                             (* -1 (((partial 3) ((partial 3) phi)) (up t0 x0 y0 z0)))
                             (/ (((partial 0) ((partial 0) phi)) (up t0 x0 y0 z0)) (expt c 2))))))
   ))

(module+ test
  (require rackunit/text-ui)
  (run-tests the-tests))