#lang racket/base

(require rackunit
         "../../kernel-gnrc.rkt"
         (only-in racket/base [sqrt rkt:sqrt])
         "../../units/units.rkt"
         "../helper.rkt")

(provide the-tests)
(define the-tests
  (test-suite
   "units/units"
   (test-case
    "unitless?"
    (check-true (unitless? &unitless))
    (check-false (unitless? 1))
    (check-false (unitless? '())))
   (test-case
    "make-unit"
    (define system (gensym))
    (check-equal? (make-unit system the-empty-vector 1) &unitless)
    (check-equal? (make-unit system the-empty-vector 2) (list unit-type-tag system the-empty-vector 2))
    (check-equal? (make-unit system #(0 0) 1) &unitless)
    (check-equal? (make-unit system #(1 2) 1) (list unit-type-tag system #(1 2) 1))
    (check-equal? (make-unit system #(1 2) 5/2) (list unit-type-tag system #(1 2) 5/2))
    (check-equal? (unit-system (make-unit system #(1 2) 5/2)) system)
    (check-equal? (unit-system &unitless) #t)
    (check-equal? (unit-exponents (make-unit system #(1 2) 5/2)) #(1 2))
    (check-equal? (unit-exponents &unitless) the-empty-vector)
    (check-equal? (unit-scale (make-unit system #(1 2) 5/2)) 5/2)
    (check-equal? (unit-scale &unitless) 1)
    (check-true (units? &unitless))
    (check-true (units? (make-unit system #(1 2) 5/2)))
    (check-false (units? system))
    (check-false (units? 1)))
   (test-case
    "same-dimensions?"
    (define test-fct same-dimensions?)
    (define system (gensym))
    (define other (gensym))
    (define U (make-unit system #(1 2) 5/2))
    (check-true  (test-fct &unitless &unitless))
    (check-false (test-fct &unitless (make-unit system #(1 2) 5/2)))
    (check-false (test-fct U &unitless))
    (check-true  (test-fct U U))
    (check-true  (test-fct U (make-unit system #(1 2) 5/2)))
    (check-true  (test-fct U (make-unit other #(1 2) 5/2)))
    (check-true  (test-fct (make-unit system #(1 2) 5/2) (make-unit system #(1 2) 3)))
    (check-true  (test-fct (make-unit system #(1 2) 5/2) (make-unit system #(1 2) 2)))
    (check-false (test-fct (make-unit system #(2 1) 5/2) (make-unit system #(1 2) 5/2)))
    (check-false (test-fct (make-unit system #(1 2 3) 5/2) (make-unit system #(1 2) 3)))
    (check-false (test-fct (make-unit system #(1 2) 5/2) (make-unit system #(1 2 3) 3))))
   (test-case
    "same-units?"
    (define test-fct same-units?)
    (define system (gensym))
    (define other (gensym))
    (define U (make-unit system #(1 2) 5/2))
    (check-true  (test-fct &unitless &unitless))
    (check-false (test-fct &unitless (make-unit system #(1 2) 5/2)))
    (check-false (test-fct U &unitless))
    (check-true  (test-fct U U))
    (check-true  (test-fct U (make-unit system #(1 2) 5/2)))
    (check-false (test-fct U (make-unit other #(1 2) 5/2)))
    (check-false (test-fct (make-unit system #(1 2) 5/2) (make-unit system #(1 2) 3)))
    (check-false (test-fct (make-unit system #(1 2) 5/2) (make-unit system #(1 2) 2)))
    (check-false (test-fct (make-unit system #(2 1) 5/2) (make-unit system #(1 2) 5/2)))
    (check-false (test-fct (make-unit system #(1 2 3) 5/2) (make-unit system #(1 2) 3)))
    (check-false (test-fct (make-unit system #(1 2) 5/2) (make-unit system #(1 2 3) 3))))
   (test-case
    "<-units?"
    (define test-fct <-units?)
    (define system (gensym))
    (define other (gensym))
    (define U (make-unit system #(1 2) 5/2))
    (check-true  (test-fct &unitless &unitless))
    (check-false (test-fct &unitless (make-unit system #(1 2) 5/2)))
    (check-false (test-fct U &unitless))
    (check-true  (test-fct U U))
    (check-false (test-fct U (make-unit system #(1 2) 5/2)))
    (check-false (test-fct U (make-unit other #(1 2) 5/2)))
    (check-true  (test-fct (make-unit system #(1 2) 5/2) (make-unit system #(1 2) 3)))
    (check-false (test-fct (make-unit system #(1 2) 5/2) (make-unit system #(1 2) 2)))
    (check-false (test-fct (make-unit system #(2 1) 5/2) (make-unit system #(1 2) 5/2)))
    (check-false (test-fct (make-unit system #(1 2 3) 5/2) (make-unit system #(1 2) 3)))
    (check-false (test-fct (make-unit system #(1 2) 5/2) (make-unit system #(1 2 3) 3))))
   (test-case
    "<=-units?"
    (define test-fct <=-units?)
    (define system (gensym))
    (define other (gensym))
    (define U (make-unit system #(1 2) 5/2))
    (check-true  (test-fct &unitless &unitless))
    (check-false (test-fct &unitless (make-unit system #(1 2) 5/2)))
    (check-false (test-fct U &unitless))
    (check-true  (test-fct U U))
    (check-true  (test-fct U (make-unit system #(1 2) 5/2)))
    (check-false (test-fct U (make-unit other #(1 2) 5/2)))
    (check-true  (test-fct (make-unit system #(1 2) 5/2) (make-unit system #(1 2) 3)))
    (check-false (test-fct (make-unit system #(1 2) 5/2) (make-unit system #(1 2) 2)))
    (check-false (test-fct (make-unit system #(2 1) 5/2) (make-unit system #(1 2) 5/2)))
    (check-false (test-fct (make-unit system #(1 2 3) 5/2) (make-unit system #(1 2) 3)))
    (check-false (test-fct (make-unit system #(1 2) 5/2) (make-unit system #(1 2 3) 3))))
   (test-case
    ">-units?"
    (define test-fct >-units?)
    (define system (gensym))
    (define other (gensym))
    (define U (make-unit system #(1 2) 5/2))
    (check-true  (test-fct &unitless &unitless))
    (check-false (test-fct &unitless (make-unit system #(1 2) 5/2)))
    (check-false (test-fct U &unitless))
    (check-true  (test-fct U U))
    (check-false (test-fct U (make-unit system #(1 2) 5/2)))
    (check-false (test-fct U (make-unit other #(1 2) 5/2)))
    (check-false (test-fct (make-unit system #(1 2) 5/2) (make-unit system #(1 2) 3)))
    (check-true  (test-fct (make-unit system #(1 2) 5/2) (make-unit system #(1 2) 2)))
    (check-false (test-fct (make-unit system #(2 1) 5/2) (make-unit system #(1 2) 5/2)))
    (check-false (test-fct (make-unit system #(1 2 3) 5/2) (make-unit system #(1 2) 3)))
    (check-false (test-fct (make-unit system #(1 2) 5/2) (make-unit system #(1 2 3) 3))))
   (test-case
    ">=-units?"
    (define test-fct >=-units?)
    (define system (gensym))
    (define other (gensym))
    (define U (make-unit system #(1 2) 5/2))
    (check-true  (test-fct &unitless &unitless))
    (check-false (test-fct &unitless (make-unit system #(1 2) 5/2)))
    (check-false (test-fct U &unitless))
    (check-true  (test-fct U U))
    (check-true  (test-fct U (make-unit system #(1 2) 5/2)))
    (check-false (test-fct U (make-unit other #(1 2) 5/2)))
    (check-false (test-fct (make-unit system #(1 2) 5/2) (make-unit system #(1 2) 3)))
    (check-true  (test-fct (make-unit system #(1 2) 5/2) (make-unit system #(1 2) 2)))
    (check-false (test-fct (make-unit system #(2 1) 5/2) (make-unit system #(1 2) 5/2)))
    (check-false (test-fct (make-unit system #(1 2 3) 5/2) (make-unit system #(1 2) 3)))
    (check-false (test-fct (make-unit system #(1 2) 5/2) (make-unit system #(1 2 3) 3))))
   (test-case
    "*units?"
    (define system (gensym))
    (define other (gensym))
    (define U1 (make-unit system #(1 2) 5/2))
    (define U2 (make-unit system #(2 1) 3))
    (define U3 (make-unit other #(2 1) 5/2))
    (check-equal? (*units &unitless &unitless) &unitless)
    (check-equal? (*units U1 &unitless) U1)
    (check-equal? (*units &unitless U1) U1)
    (check-equal? (*units U1 (make-unit system #(0 0) 2)) (make-unit system #(1 2) 5))
    (check-equal? (*units (make-unit system #(0) 2) U1) (make-unit system #(1 2) 5))
    (check-equal? (*units U1 U2) (make-unit system #(3 3) 15/2))
    (check-equal? (*units U2 U1) (make-unit system #(3 3) 15/2))
    (check-exn #px"assertion failed: " (λ () (*units U1 U3)))
    (check-exn #px"assertion failed: " (λ () (*units U1 (make-unit system #(1) 2)))))
   (test-case
    "invert-units"
    (define system (gensym))
    (check-equal? (invert-units &unitless) &unitless)
    (check-equal? (invert-units (make-unit system #() 2)) (make-unit system #() 1/2))
    (check-equal? (invert-units (make-unit system #(1 2) 5/2)) (make-unit system #(-1 -2) 2/5)))
   (test-case
    "/units"
    (define system (gensym))
    (define other (gensym))
    (define U1 (make-unit system #(1 2) 5/2))
    (define U2 (make-unit system #(2 1) 3))
    (define U3 (make-unit other #(2 1) 5/2))
    (check-equal? (/units &unitless &unitless) &unitless)
    (check-equal? (/units U1 &unitless) U1)
    (check-equal? (/units &unitless U1) (make-unit system #(-1 -2) 2/5))
    (check-equal? (/units U1 (make-unit system #(0 0) 2)) (make-unit system #(1 2) 5/4))
    (check-equal? (/units (make-unit system #(0) 2) U1) (make-unit system #(-1 -2) 4/5))
    (check-equal? (/units U1 U2) (make-unit system #(-1 1) 5/6))
    (check-equal? (/units U2 U1) (make-unit system #(1 -1) 6/5))
    (check-exn #px"assertion failed: " (λ () (*units U1 U3)))
    (check-exn #px"assertion failed: " (λ () (*units U1 (make-unit system #(1) 2)))))
   (test-case
    "expt-units"
    (define system (gensym))
    (check-equal? (expt-units &unitless 2) &unitless)
    (check-equal? (expt-units (make-unit system #() 2) 2) (make-unit system #() 4))
    (check-equal? (expt-units (make-unit system #(1 2) 5/2) 2) (make-unit system #(2 4) 25/4))
    (check-equal? (expt-units &unitless -1/2) &unitless)
    (check-equal? (expt-units (make-unit system #() 2) -1/2) (make-unit system #() (/ (rkt:sqrt 2) 2)))
    (check-equal? (expt-units (make-unit system #(1 2) 5/2) -1/2) (make-unit system #(-1/2 -1) (rkt:sqrt 2/5)))
    (check-exn #px"Not a unit -- EXPT" (λ () (expt-units 5 5))))
   (test-case
    "solve-linear"
    (define system (gensym))
    (define other (gensym))
    (define U1 (make-unit system #(1 2) 5/2))
    (define U2 (make-unit system #(2 1) 3))
    (define U3 (make-unit other #(2 1) 5/2))
    (units:assign-operations)
    (check-equal? (solve-linear &unitless U1) (make-unit system #(1 2) 5/2))
    (check-equal? (solve-linear-left U2 U1) (make-unit system #(-1 1) 5/6)))
   ))

(module+ test
  (require rackunit/text-ui)
  (run-tests the-tests))